Repository googleinterns/step190-2020, pull requests merged in 2020-07, with the labels that each got.

#14 Scrape civicdata
  .gitignore
  src/main/webapp/getStateIDs.sh
  src/main/webapp/script.js
Labels: Priority: High, Status: Completed, Type: Feature

#19 Style the election list
  src/main/webapp/index.html
  src/main/webapp/list.html
  src/main/webapp/style.css
Labels: Priority: High, Status: Completed, Type: Feature

#17 State selection page UI
  .gitignore
  src/main/webapp/electionlist.html
  src/main/webapp/getStateIDs.sh
  src/main/webapp/index.html
  src/main/webapp/script.js
  src/main/webapp/style.css
Labels: Priority: High, Status: Review Needed, Type: Feature

#20 Election servlet
  src/main/java/com/google/sps/servlets/ElectionServlet.java
Labels: Priority: High, Status: Review Needed

#23 Add plugin to format java files on mvn commands
  pom.xml
Labels: Priority: High, Status: Review Needed

#26 Election entity modeled off of the description in the spec.
  src/main/java/com/google/sps/data/Election.java
Labels: Priority: High, Status: Review Needed

#27 Elections datastore
  src/main/java/com/google/sps/data/Election.java
  src/main/java/com/google/sps/servlets/ElectionServlet.java
Labels: Priority: High, Status: Review Needed, Type: Feature

#29 Comment formatting
  .env
  pom.xml
  src/main/java/com/google/sps/servlets/ElectionServlet.java
Labels: Priority: Critical

#28 List elections from the data returned from ElectionServlet
  src/main/java/com/google/sps/servlets/ElectionServlet.java
  src/main/webapp/electionlist.html
  src/main/webapp/script.js
  src/main/webapp/style.css
Labels: Priority: High, Status: Completed, Type: Feature

#31 Cron job adjustments
  pom.xml
  src/main/java/com/google/sps/data/Election.java
  src/main/java/com/google/sps/servlets/ElectionServlet.java
  src/main/java/com/google/sps/servlets/GetElectionServlet.java
Labels: Priority: Critical, Status: Review Needed

#43 Apply Builder pattern to Election object
  pom.xml
  src/main/java/com/google/sps/data/Election.java
  src/main/java/com/google/sps/servlets/ElectionServlet.java
  src/test/java/com/google/sps/integration/ExampleIT.java
Labels: Priority: Medium, Status: Review Needed, Type: Feature

#47 Make remaining POJO's for DataStore
  src/main/java/com/google/sps/data/Candidate.java
  src/main/java/com/google/sps/data/PollingStation.java
  src/main/java/com/google/sps/data/Position.java
  src/main/java/com/google/sps/data/Proposition.java
Labels: Priority: High, Status: Review Needed, Type: Feature
