Repository googleinterns/step190-2020, pull requests merged in 2020-08, with the labels that each got.

#70 Put Election and Candidate info into Datastore (5.0)
  pom.xml
  src/main/java/com/google/sps/data/Candidate.java
  src/main/java/com/google/sps/data/Contest.java
  src/main/java/com/google/sps/data/Election.java
  src/main/java/com/google/sps/data/PollingStation.java
  src/main/java/com/google/sps/data/Position.java
  src/main/java/com/google/sps/data/Proposition.java
  src/main/java/com/google/sps/servlets/ElectionServlet.java
  src/main/java/com/google/sps/servlets/InfoCardServlet.java
  src/main/java/com/google/sps/servlets/PollingStationServlet.java
  src/main/java/com/google/sps/servlets/ServletUtils.java
  src/main/webapp/config.js
  src/main/webapp/electionlist.html
  src/main/webapp/index.html
  src/test/java/com/google/sps/data/ElectionTest.java
  src/test/java/com/google/sps/integration/ExampleIT.java
  src/test/java/com/google/sps/integration/integration_db.bin
  src/test/java/com/google/sps/servlets/ElectionServletTest.java
Labels: cla: yes

#71 Center vertical alignment of logo and widen address input bar
  src/main/webapp/electionInfo.html
  src/main/webapp/electionlist.html
  src/main/webapp/index.html
  src/main/webapp/style.css
Labels: Priority: Low, Status: Completed, Type: Bug, cla: yes

#66 Add continuity between second and third pages so that query string no…
  src/main/webapp/auto-complete.js
  src/main/webapp/election-info.js
  src/main/webapp/election-list.js
  src/main/webapp/electionInfo.html
  src/main/webapp/electionlist.html
  src/main/webapp/index.html
  src/main/webapp/script.js
  src/main/webapp/style.css
  src/main/webapp/welcome-page.js
  src/test/java/com/google/sps/ElectionInfoIT
  src/test/java/com/google/sps/integration/ElectionInfoIT.java
  src/test/java/com/google/sps/integration/ElectionListIT.java
  src/test/java/com/google/sps/integration/WelcomePageIT.java
Labels: Priority: High, Status: Review Needed, Type: Feature, cla: yes

#74 Fix for small typo in the JavaScript due to issues with merging branc…
  src/main/webapp/election-info.js
Labels: cla: yes

#75 Resolving more typos between branches.
  src/main/webapp/election-list.js
  src/main/webapp/electionlist.html
Labels: cla: yes

#77 Fix Continuous Integration tests
  .gitignore
  pom.xml
Labels: cla: yes

#78 Debugging redirection function so that second and third page connect.
  pom.xml
  src/main/java/com/google/sps/servlets/ServletUtils.java
  src/main/webapp/election-list.js
  src/main/webapp/electionlist.html
  src/test/java/com/google/sps/integration/ElectionListIT.java
  src/test/java/com/google/sps/integration/integration_db.bin
Labels: cla: yes

#72 Test util functions in ServletUtils.java
  src/main/java/com/google/sps/servlets/ServletUtils.java
  src/test/java/com/google/sps/data/ElectionTest.java
  src/test/java/com/google/sps/unit/ServletUtilsTest.java
Labels: Priority: Medium, cla: yes

#73 Contest servlet
  pom.xml
  src/main/java/com/google/sps/data/Contest.java
  src/main/java/com/google/sps/servlets/ContestsServlet.java
  src/main/webapp/config.js
  src/main/webapp/election-info.js
  src/test/java/com/google/sps/servlets/ContestServletTest.java
Labels: cla: no

#84 Ignore any config.js in entire repo
  .gitignore
Labels: cla: yes

#79 Polling station class and servlet
  src/main/java/com/google/sps/data/Election.java
  src/main/java/com/google/sps/data/PollingStation.java
  src/main/java/com/google/sps/servlets/InfoCardServlet.java
  src/main/java/com/google/sps/servlets/PollingStationServlet.java
  src/test/java/com/google/sps/ElectionInfoIT
  src/test/java/com/google/sps/data/ElectionTest.java
  src/test/java/com/google/sps/data/PollingStationTest.java
  src/test/java/com/google/sps/servlets/ElectionServletTest.java
  src/test/java/com/google/sps/servlets/PollingStationServletTest.java
Labels: Priority: High, Status: Review Needed, cla: yes

#81 Get Referendum data
  src/main/java/com/google/sps/data/Candidate.java
  src/main/java/com/google/sps/data/Contest.java
  src/main/java/com/google/sps/data/Election.java
  src/main/java/com/google/sps/data/PollingStation.java
  src/main/java/com/google/sps/data/Proposition.java
  src/main/java/com/google/sps/data/Referendum.java
  src/main/java/com/google/sps/servlets/ContestsServlet.java
  src/main/java/com/google/sps/servlets/ElectionServlet.java
  src/main/java/com/google/sps/servlets/ServletUtils.java
  src/main/webapp/electionlist.html
  src/main/webapp/index.html
  src/test/java/com/google/sps/data/ElectionTest.java
  src/test/java/com/google/sps/data/ReferendumTest.java
  src/test/java/com/google/sps/integration/integration_db.bin
  src/test/java/com/google/sps/servlets/ContestServletTest.java
  src/test/java/com/google/sps/servlets/ElectionServletTest.java
  src/test/java/com/google/sps/unit/ServletUtilsTest.java
Labels: Priority: High, Status: Review Needed, Type: Feature, cla: yes

#87 Add Candidate info to ContestServlet GET response
  src/main/java/com/google/sps/data/Candidate.java
  src/main/java/com/google/sps/data/Contest.java
  src/main/java/com/google/sps/data/PollingStation.java
  src/main/java/com/google/sps/data/Referendum.java
  src/main/java/com/google/sps/servlets/ContestsServlet.java
  src/main/java/com/google/sps/servlets/ServletUtils.java
  src/test/java/com/google/sps/servlets/ContestServletTest.java
Labels: cla: yes

#88 Fix broken Maven build by updating integration_db.bin
  src/test/java/com/google/sps/integration/integration_db.bin
Labels: cla: yes

#90 Stop excluding config.js to fix 404 error
  src/main/webapp/WEB-INF/appengine-web.xml
Labels: cla: yes

#93 Create collapsible description sections for the info cards
  src/main/webapp/election-info.js
  src/main/webapp/electionInfo.html
  src/main/webapp/style.css
Labels: cla: yes

#92 Candidate and contests tests
  .gitignore
  src/main/java/com/google/sps/data/Candidate.java
  src/main/java/com/google/sps/data/Contest.java
  src/main/java/com/google/sps/servlets/ContestsServlet.java
  src/test/java/com/google/sps/data/CandidateTest.java
  src/test/java/com/google/sps/data/ContestTest.java
  src/test/java/com/google/sps/data/ElectionTest.java
Labels: cla: yes

#97 Create UI for MVP.
  .gitignore
  src/main/java/com/google/sps/data/Candidate.java
  src/main/java/com/google/sps/data/Election.java
  src/main/java/com/google/sps/data/PollingStation.java
  src/main/java/com/google/sps/servlets/InfoCardServlet.java
  src/main/java/com/google/sps/servlets/PollingStationServlet.java
  src/main/webapp/auto-complete.js
  src/main/webapp/election-info.js
  src/main/webapp/electionInfo.html
  src/main/webapp/style.css
  src/test/java/com/google/sps/data/PollingStationTest.java
  src/test/java/com/google/sps/integration/integration_db.bin
Labels: cla: yes

#104 Add exception handling tests for fromJSONObject method in Candidate
  src/test/java/com/google/sps/data/CandidateTest.java
Labels: cla: yes

#106 Delete duplicate
  src/main/webapp/election-info.js
Labels: cla: yes

#108 Polling station tests
  .gitignore
  src/main/java/com/google/sps/data/Contest.java
  src/main/java/com/google/sps/data/Election.java
  src/main/java/com/google/sps/data/PollingStation.java
  src/main/java/com/google/sps/servlets/ContestsServlet.java
  src/main/java/com/google/sps/servlets/ElectionServlet.java
  src/main/java/com/google/sps/servlets/InfoCardServlet.java
  src/main/java/com/google/sps/servlets/ServletUtils.java
  src/main/webapp/election-info.js
  src/main/webapp/election-list.js
  src/main/webapp/electionlist.html
  src/test/java/com/google/sps/data/ElectionTest.java
  src/test/java/com/google/sps/data/PollingStationTest.java
  src/test/java/com/google/sps/integration/ElectionInfoIT.java
  src/test/java/com/google/sps/integration/ElectionListIT.java
  src/test/java/com/google/sps/integration/ExampleIT.java
  src/test/java/com/google/sps/integration/integration_db.bin
Labels: cla: yes

#107 Delete all data from voterInfoQuery on PUT request to avoid repeated data
  src/main/java/com/google/sps/servlets/ElectionServlet.java
  src/main/java/com/google/sps/servlets/InfoCardServlet.java
  src/main/java/com/google/sps/servlets/ServletUtils.java
  src/test/java/com/google/sps/integration/integration_db.bin
Labels: Priority: High, Status: Review Needed, Type: Bug, cla: yes

#112 Loading icon
  src/main/webapp/election-info.js
  src/main/webapp/electionInfo.html
  src/main/webapp/style.css
Labels: cla: yes

#110 Catch JSONException when referendumSubtitle does not exist
  pom.xml
  src/main/java/com/google/sps/data/Referendum.java
  src/test/java/com/google/sps/data/ReferendumTest.java
Labels: Type: Bug, cla: yes

#109 Election info error screen when no Election ID is provided
  src/main/webapp/election-info.js
  src/main/webapp/electionInfo.html
  src/main/webapp/style.css
  src/test/java/com/google/sps/integration/ElectionInfoIT.java
  src/test/java/com/google/sps/integration/ElectionListIT.java
  src/test/java/com/google/sps/integration/integration_db.bin
Labels: cla: yes

#114 Make Candiate Campaign URLs Clickable
  src/main/webapp/election-info.js
  src/main/webapp/electionInfo.html
Labels: cla: yes

#120 Move map container outside of Handlebars template and zoom in more.
  src/main/webapp/election-info.js
  src/main/webapp/electionInfo.html
Labels: cla: yes

#121 Add Social Channels Information to Candidate Object and Candidate Info Card
  src/main/java/com/google/sps/data/Candidate.java
  src/main/webapp/electionInfo.html
  src/test/java/com/google/sps/data/CandidateTest.java
  src/test/java/com/google/sps/data/ContestTest.java
  src/test/java/com/google/sps/integration/ElectionListIT.java
  src/test/java/com/google/sps/servlets/ContestServletTest.java
Labels: cla: yes

#119 Add Sources text to bottom of info cards
  src/main/java/com/google/sps/data/Contest.java
  src/main/java/com/google/sps/data/Referendum.java
  src/main/webapp/electionInfo.html
  src/main/webapp/style.css
  src/test/java/com/google/sps/data/ContestTest.java
  src/test/java/com/google/sps/data/ReferendumTest.java
  src/test/java/com/google/sps/integration/integration_db.bin
  src/test/java/com/google/sps/servlets/ContestServletTest.java
Labels: cla: yes

#126 Referendum URL Functionality
  src/main/java/com/google/sps/data/Referendum.java
  src/main/webapp/electionInfo.html
  src/test/java/com/google/sps/data/ReferendumTest.java
  src/test/java/com/google/sps/integration/integration_db.bin
  src/test/java/com/google/sps/servlets/ContestServletTest.java
Labels: cla: yes

#125 Test retrieval of entities deleted from Datastore
  src/main/java/com/google/sps/data/Contest.java
  src/main/java/com/google/sps/data/Referendum.java
  src/test/java/com/google/sps/servlets/ContestServletTest.java
Labels: cla: yes

#124 Additional support for polling station UI
  src/main/java/com/google/sps/data/PollingStation.java
  src/main/java/com/google/sps/data/Referendum.java
  src/main/webapp/election-info.js
  src/main/webapp/electionInfo.html
  src/main/webapp/style.css
  src/test/java/com/google/sps/data/PollingStationTest.java
  src/test/java/com/google/sps/integration/ElectionListIT.java
  src/test/java/com/google/sps/integration/ExampleIT.java
  src/test/java/com/google/sps/integration/integration_db.bin
  src/test/java/com/google/sps/servlets/PollingStationServletTest.java
Labels: cla: yes

#127 Show error text on API 404 error
  src/main/java/com/google/sps/servlets/ElectionServlet.java
  src/main/java/com/google/sps/servlets/InfoCardServlet.java
  src/main/java/com/google/sps/servlets/ServletUtils.java
  src/main/webapp/election-info.js
  src/main/webapp/election-list.js
  src/main/webapp/electionInfo.html
  src/main/webapp/style.css
  src/test/java/com/google/sps/integration/EndToEndIT.java
  src/test/java/com/google/sps/integration/integration_db.bin
Labels: cla: yes

#131 Info card front-end new features
  src/main/java/com/google/sps/data/Candidate.java
  src/main/webapp/election-info.js
  src/main/webapp/electionInfo.html
  src/main/webapp/style.css
Labels: cla: yes

#130 Incorporate data from WeVote and FVAP APIs
  pom.xml
  src/main/java/com/google/sps/data/Candidate.java
  src/main/java/com/google/sps/servlets/ContestsServlet.java
  src/main/java/com/google/sps/servlets/DeadlinesServlet.java
  src/main/java/com/google/sps/servlets/ElectionServlet.java
  src/main/java/com/google/sps/servlets/InfoCardServlet.java
  src/main/java/com/google/sps/servlets/PollingStationServlet.java
  src/main/java/com/google/sps/servlets/ServletUtils.java
  src/main/webapp/election-info.js
  src/main/webapp/electionInfo.html
  src/main/webapp/style.css
  src/test/java/com/google/sps/data/CandidateTest.java
  src/test/java/com/google/sps/integration/integration_db.bin
  src/test/java/com/google/sps/servlets/DeadlineServletTest.java
Labels: cla: yes

#133 Key deadlines show on page load and address input is one input field
  src/main/java/com/google/sps/servlets/DeadlinesServlet.java
  src/main/webapp/auto-complete.js
  src/main/webapp/election-info.js
  src/main/webapp/electionInfo.html
  src/main/webapp/style.css
  src/test/java/com/google/sps/integration/integration_db.bin
  src/test/java/com/google/sps/servlets/DeadlineServletTest.java
Labels: cla: yes

#136 Handle small bugs in UI for dates and deadlines.
  src/main/java/com/google/sps/servlets/DeadlinesServlet.java
  src/main/webapp/election-info.js
  src/test/java/com/google/sps/integration/ElectionInfoIT.java
  src/test/java/com/google/sps/integration/ElectionListIT.java
  src/test/java/com/google/sps/integration/EndToEndIT.java
  src/test/java/com/google/sps/integration/integration_db.bin
Labels: cla: yes

#138 IT for presence of deadlines upon page load.
  src/main/webapp/electionInfo.html
  src/test/java/com/google/sps/integration/ElectionInfoIT.java
  src/test/java/com/google/sps/integration/ElectionListIT.java
Labels: cla: yes

#139 Add favicon.io
  src/main/webapp/favicon.io
Labels: cla: yes

#142 Make favicon appear on site tab
  src/main/webapp/electionInfo.html
  src/main/webapp/electionlist.html
  src/main/webapp/index.html
Labels: cla: yes

#140 Add error handling for invalid state on electionList.html
  src/main/webapp/election-list.js
  src/main/webapp/electionInfo.html
  src/main/webapp/electionlist.html
  src/main/webapp/style.css
Labels: cla: yes

#143 Display info text if candidate does not have additional card data
  src/main/webapp/election-info.js
  src/main/webapp/electionInfo.html
Labels: cla: yes
